### ISSUE TITLE
Auto-detect grub2-mkrescue named grub-mkrescue

### ISSUE THREAD

**Issue by Arondight** [hartwork/grub2-theme-preview#11]
for example, in archlinux **grub2** is packaged with name **grub**, also all executable files in package **grub** begin with string "grub-". user should make a link manually to keep script run correctly.
in a word `grub2-mkrescue` is named by `grub-mkrescue` in some distro, but the script can not identify it.

> ~ » pacman -Ql grub | grep -oP '(?<=bin\/).+$'
> grub-bios-setup
> grub-editenv
> grub-file
> grub-fstest
> grub-glue-efi
> grub-install
> grub-kbdcomp
> grub-macbless
> grub-menulst2cfg
> grub-mkconfig
> grub-mkfont
> grub-mkimage
> grub-mklayout
> grub-mknetdir
> grub-mkpasswd-pbkdf2
> grub-mkrelpath
> grub-mkrescue
> grub-mkstandalone
> grub-mount
> grub-ofpathname
> grub-probe
> grub-reboot
> grub-render-label
> grub-script-check
> grub-set-default
> grub-sparc64-setup
> grub-syslinux2cfg

**Comment by hartwork** [comment]
Hi!
True, there is no auto-detection, yet. Before we have that, you could pass `--grub2-mkrescue grub-mkrescue` for a workaround.

**Comment by hartwork** [comment]
I think d052679bad5315848793d338d2d29e5ba5b48847 obsoletes need for auto-detection due to the change in default. If it's still needed, please re-open this ticket.
