### ISSUE TITLE
[openSUSE] Just wanted to let you know i put v. 131 in a rpm on openSUSE OBS:

### ISSUE THREAD

**Issue by revealed** [hartwork/grub2-theme-preview#12]
https://build.opensuse.org/package/show/home:revealed/grub2-theme-preview

Im only doing such as hobby only. Your script was very useful for me, when modding my own grub2 theme. I decided to put it into a RPM.

https://build.opensuse.org/package/show/home:revealed/grub2-theme-preview

Much appereciated.

Greetings from Bavaria.

**Comment by hartwork** [comment]
Cool, thanks for the notification.

**Comment by hartwork** [comment]
@revealed I just released 1.3.2. Could you update the openSUSE package?
