### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by andros705** [hartwork/grub2-theme-preview#15]
There is no LICENSE file and I can't find the license information.

**Comment by hartwork** [comment]
All `.py` files have `Licensed under GPL v2 or later` in their header.

**Comment by andros705** [comment]
All right, thanks!
Also I've noticed it says "GPL-2+" on [x11-misc/grub2-theme-preview – Gentoo Packages](https://packages.gentoo.org/packages/x11-misc/grub2-theme-preview) but thanks for your answer.
