### ISSUE TITLE
grub2-theme-preview missing in 1.4x

### ISSUE THREAD

**Issue by TediCreations** [hartwork/grub2-theme-preview#17]
Between 1.32 and 1.4 there is a big change and in the 1.4x the version control omitted the grub2-theme-preview.

**Comment by hartwork** [comment]
Hi!

[This line in `setup.py`](https://github.com/hartwork/grub2-theme-preview/blob/93c9e146cd13d298a147a6c7f74cdda1c6d488cb/setup.py#L28) ensures that file `grub2-theme-preview` is generated during installation by setuptools.

If you're using a Git clone for some reason, you can use `python setup.py develop` or `pip install -e .` to generate that file like this:
```console
# cd "$(mktemp -d)"
# git clone https://github.com/hartwork/grub2-theme-preview/
# cd grub2-theme-preview/
# virtualenv --python=python3.7 py37
# source py37/bin/activate
# pip install -e .
# which grub2-theme-preview
/tmp/tmp.vDFHypqdzR/grub2-theme-preview/py37/bin/grub2-theme-preview
```

Another way of running grub2-theme-preview that doesn't even need that file is
```
python -m grub2_theme_preview
```
when installed or
```
PYTHONPATH=. python -m grub2_theme_preview
```
from a Git clone.

Does that answer your question?

**Comment by hartwork** [comment]
@TediCreations ?

**Comment by TediCreations** [comment]
Hi thanks for the answer.
