### ISSUE TITLE
Stuck on "Booting from Hard Disk"

### ISSUE THREAD

**Issue by mateosss** [hartwork/grub2-theme-preview#18]
Hi, I'm unable to run it on Lubuntu 18.04, I did as follows:

```sh
sudo su
pip install grub2_theme_preview
apt install xorriso
```
The script only seemed to complain about `xorriso` as I already seem to have qemu (or at least I have 60+ commands starting with `qemu-`)

And after running what the terminal in the image shows, I got stuck in this.

![2020-06-27-203559_946x627_scrot](https://user-images.githubusercontent.com/5622899/85934193-d330bf00-b8b5-11ea-8c59-abd26dfeb6e2.png)

Do you have any ideas?

**Comment by hartwork** [comment]
Hi!

I have added an option `--plain-rescue-image` for situations like this. Please try:
```
# grub2-theme-preview --verbose --debug --plain-rescue-image --grub-cfg /dev/null /var/empty
```
If things go well, you should end up in a grub shell like this:
![grub_Screenshot_20200628_021041](https://user-images.githubusercontent.com/1577132/85934578-9fb95900-b8e4-11ea-9bb3-aca2bc123145.png)

Is it still hanging?

**Comment by mateosss** [comment]
That command gave python error and finished because /var/empty does not exist, so I tried it again with the theme path instead and got stuck again.

![2020-06-28-122128_1920x1080_scrot](https://user-images.githubusercontent.com/5622899/85951527-061c9680-b93a-11ea-974d-0518fa824f22.png)

**Comment by hartwork** [comment]
I tried both with rescue images generated by Debian sid's GRUB 2.04 and Ubuntu bionic's GRUB 2.02 now — both worked. And then I noticed… "efi" in your output: It's because of EFI. Give me two hours and with some luck I have a fix until then.

**Comment by hartwork** [comment]
I believe I have a fix in Git `master` now. Here's one way to see if the fix works:

```console
cd "$(mktemp -d)"
git clone https://github.com/hartwork/grub2-theme-preview
cd grub2-theme-preview
virtualenv --python=python3.7 py37
source py37/bin/activate
pip install -e .  # into the virtualenv
sudo apt install omvf  # provides an EFI bios image
grub2-theme-preview --verbose --debug --plain-rescue-image --grub-cfg /dev/null /boo/grub/themes/Matter/
```

Does it work?

**Comment by mateosss** [comment]
There it is! It works almost perfect now, the only problem is the font not properly being shown, but maybe I should open another issue for that?

![2020-06-28-143526_1920x1080_scrot](https://user-images.githubusercontent.com/5622899/85954283-aaa7d400-b94c-11ea-992e-2fa8bc1affd7.png)

**Comment by hartwork** [comment]
Cool! For the font thing: Any ideas what might be wrong? The screenshot says that font googlesans.pf2 is copied. I would need help with understanding what the correct behavior would be. But it's probabably a bug either way.

I'll close this one right here and push a new release in a minute.
