### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by DarkoGNU** [hartwork/grub2-theme-preview#20]
QEMU uses 128MB of memory by default. Without increasing this value, I can't test my themes

`grub2-theme-preview TestTheme/`:
![Default resolution](https://user-images.githubusercontent.com/42816979/87246243-676d5b00-c44c-11ea-97e7-1407aaddb6ce.png)
After changing the resolution to 1080p, I see an out of memory error before getting to the menu
`grub2-theme-preview --resolution 1920x1080 TestTheme/`:
![1080p](https://user-images.githubusercontent.com/42816979/87246257-84099300-c44c-11ea-9ac2-291c081e9ce3.png)
When I launch the image manually, assigning 256MB of memory, everything works perfectly
`qemu-system-x86_64 -drive file=/tmp/tmpp3to5qpq/grub2_theme_demo_copy.img,index=0,media=disk,format=raw -bios /usr/share/edk2-ovmf/x64/OVMF_CODE.fd -m 256M`:
![1080p, 256M](https://user-images.githubusercontent.com/42816979/87246268-9aafea00-c44c-11ea-9b8b-3e3d56d1cd71.png)
([image used](https://user-images.githubusercontent.com/42816979/87246675-36425a00-c44f-11ea-80ae-c4096fa57581.png))

Whether it works - it also depends on the image used. For example, [this](https://user-images.githubusercontent.com/42816979/87246764-a355ef80-c44f-11ea-8429-b226b2dc1e3e.png) ([uncropped](https://safebooru.donmai.us/posts/3360015?tags=kuroneko-chan_%28satou%29+), in case anyone is interested) image works with the default settings, even though it is bigger by 0.3MB. It still doesn't work at 1920x1080 without increasing RAM
`grub2-theme-preview TestTheme/`:
![Default resolution, alt image](https://user-images.githubusercontent.com/42816979/87246817-f16af300-c44f-11ea-83bf-cbfe3b44a9a7.png)
In case you need that theme for testing for some reason: [TestTheme.zip](https://github.com/hartwork/grub2-theme-preview/files/4908524/TestTheme.zip)

**I think that you need to add an argument that allows setting the amount of memory and/or raise the default.**

Important: I use the [AUR](https://aur.archlinux.org/packages/grub2-theme-preview/) package.
EDIT: tested with the latest release from PyPI, the issue still exists

**Comment by hartwork** [comment]
Makes perfect sense, good report. It's calling QEMU asking for 256m of RAM now, and there's a new release 1.5.1 with that fix on PyPI as well. Closing as fixed, happy to re-open as needed.
