### ISSUE TITLE
Seems to work, but no boot menu shown

### ISSUE THREAD

**Issue by texxasrulez** [hartwork/grub2-theme-preview#21]
Trying out your theme previewer and it seems to be working as expected but never shows boot screen ..

usage:
`/grub2-theme-preview --verbose /path_to_my/theme/name`

Output:
~~~
INFO: Appending to fonts to load: DejaVuSansMono-08.pf2
INFO: Appending to fonts to load: DejaVuSansMono-22.pf2
INFO: Appending to fonts to load: FreeSans-22.pf2
# grub-mkrescue --directory=/usr/lib/grub/x86_64-efi --xorriso xorriso --output /tmp/tmpxqgu_eyx/grub2_theme_demo.img boot/grub/themes/DEMO/=/boot/grub/themes/blue-tiger-fractal
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:/tmp/tmpxqgu_eyx/grub2_theme_demo.img'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  162g free
Added to ISO image: directory '/'='/tmp/grub.ttA5OF'
xorriso : UPDATE :     289 files added in 1 seconds
Added to ISO image: directory '/boot/grub/themes/DEMO'='/boot/grub/themes/blue-tiger-fractal'
xorriso : UPDATE :     384 files added in 1 seconds
ISO image produced: 5632 sectors
Written to medium : 5632 sectors at LBA 0
Writing to 'stdio:/tmp/tmpxqgu_eyx/grub2_theme_demo.img' completed successfully.

INFO: Please give GRUB a moment to show up in QEMU...
# qemu-system-x86_64 -m 256 -drive file=/tmp/tmpxqgu_eyx/grub2_theme_demo.img,index=0,media=disk,format=raw -bios /usr/share/OVMF/OVMF_CODE.fd
VNC server running on 127.0.0.1:5900
~~~

It stays there and nothing else happens. 
I am running Linux Mint 20. 
Is there something I am missing?
I do thank you

**Comment by texxasrulez** [comment]
The longest I let the terminal run was well over 30 minutes one time. I am trying to check out my work, https://github.com/texxasrulez/grub2-theme-blue-linux-mint is one of them. I just created the screenshot myself in gimp which is very close to being accurate, maybe highlight color a little off. Not too bad for an old man LOL. 

I have updated to 2.0.1 and added --no-kvm and it came up for me. Resolution is off, so I just need to play with your program and see what she can do ... I appreciate your assistance.

Passing `qemu-system-x86_64 -display help` just give me an error `Invalid parameter help`
Passing `qemu-system-x86_64 --help | fgrep -A1 'default display'` returns 
               `The default display is equivalent to
                "-display gtk"`

I am going to see what this viewer can do. If there is anything else you need me to do,  don't hesitate to ask

**Comment by hartwork** [comment]
Thanks for the update. Did you try without `--no-kvm`? Is there anything left to fix?

**Comment by texxasrulez** [comment]
It works for me now and I am just passing resolution option ... Top Notch work. Sure is handy to have this tool.

**Comment by hartwork** [comment]
Okay cool, I'll close the ticket as fixed then.

**Comment by texxasrulez** [comment]
I am glad you wrote this. A HUGE time saver. I am kinda going crazy on some themes right now and will be uploading to Github. Your tool cuts time drastically and screen capture capabilities keeps me from having to mock up a screenshot.
All BS aside, if you ever need help testing or anything within my skill set, do not hesitate to ask. I have no life and have the time to help out. I especially like to help on projects I use and since I was born good looking instead of rich, I have no money to give but I will donate my time to you.

Thanks again and I hope you enjoy the rest of your week.
