### ISSUE TITLE
[EndeavourOS] ERROR: [Errno 2] OVMF image file "/usr/share/OVMF/OVMF_CODE.fd" (provided by package "ovmf") missing, please install

### ISSUE THREAD

**Issue by melorin4** [hartwork/grub2-theme-preview#26]
Installed grub2-theme-preview from the AUR but it doesn't seem to work for me. I already have all of the dependencies including ovmf installed but it gives me this error:
`# grub2-theme-preview --verbose /boot/grub/themes/EndeavourOS
INFO: Appending to fonts to load: unifont-regular-16.pf2
ERROR: [Errno 2] OVMF image file "/usr/share/OVMF/OVMF_CODE.fd" (provided by package "ovmf") missing, please install`

**Comment by hartwork** [comment]
Hi @melorin4 reading https://archlinux.org/packages/extra/any/edk2-ovmf/files/ I suppose that it's package `edk2-ovmf` and file `/usr/share/edk2-ovmf/x64/OVMF_CODE.fd` as of today. Any chance you could install that package, replace the filename in your local `grub2-theme-preview` code and report back if `grub2-theme-preview`starts up without issues then?
Thanks in advance! :pray:

**Comment by hartwork** [comment]
@melorin4 I think I made some false assumptions earlier:
- I assumed you were using Arch Linux just because you mentioned AUR without asking for confirmation.
- I assumed that the current code would use file `/usr/share/OVMF/OVMF_CODE.fd` and package `ovmf` for Arch Linux without checking.

Looking at the current code at… https://github.com/hartwork/grub2-theme-preview/blob/21655fe8f9675426577a4364a5e1be715df8a607/grub2_theme_preview/__main__.py#L304-L320 …the file path and package name seem to be already match status quo of Arch Linux.

The path you get are those used on _Debian and Ubuntu_. Could it be that you are running a _derivative of Arch Linux_ — e.g. Hyperbola, Manjaro, KaOS — rather than actual Arch? That would explain why you do not get the path you'd expect.

Which Linux distro you are using precisely? Could you share the output of command `python -m distro`?
For me, this produces:
```console
$ python -m distro
Name: Gentoo/Linux
Version: 2.7 (n/a)
Codename: n/a
```

Thanks! :pray:

**Comment by melorin4** [comment]
Yep! Sorry for not specifying before, I'm a bit new to GitHub and opening up issues, but I'm running EndeavourOS on this machine right now. 
Here's the output
`╰─$ python -m distro          
Name: EndeavourOS
Version: rolling (rolling)
Codename: rolling`

Just in case this is needed, I have the OVMF_CODE.fd file under `/usr/share/OVMF/ia32/OVMF_CODE.fd`

**Comment by hartwork** [comment]
I see, thanks!

I noticed that the current approach doesn't scale well for derivative distros like EndeavourOS if every single distro needs an entry there. So I went for a new approach in pull request #27 — trying all known patterns in order.

If you would like to give that code a try, one way would be:
```console
cd "$(mktemp -d)"
git clone --branch issue-26-fix-ovmf-image-detection-for-derivative-linux-distros https://github.com/hartwork/grub2-theme-preview
cd grub2-theme-preview/
python3 -m venv venv
source venv/bin/activate
pip install -e .
grub2-theme-preview --verbose --debug /boot/grub/themes/EndeavourOS
```

Would be great to know if this new approach works for you.

Thanks and best, Sebastian

**Comment by melorin4** [comment]
Thank you again! I tried the command again and it gave me this output:

```
╭─lorin@endeavouros /tmp/tmp.tlohnOPgvy/grub2-theme-preview ‹issue-26-fix-ovmf-image-detection-for-derivative-linux-distros*› 
╰─$ yay -S venv                                                                                                                                  1 ↵
 -> Could not find all required packages:
	venv (Target)
(venv) ╭─lorin@endeavouros /tmp/tmp.tlohnOPgvy/grub2-theme-preview ‹issue-26-fix-ovmf-image-detection-for-derivative-linux-distros*› 
(venv) ╭─lorin@endeavouros /tmp/tmp.tlohnOPgvy/grub2-theme-preview ‹issue-26-fix-ovmf-image-detection-for-derivative-linux-distros*› 
╰─$ yay -S venv                                                                                                                                  1 ↵
 -> Could not find all required packages:
	venv (Target)
(venv) ╭─lorin@endeavouros /tmp/tmp.tlohnOPgvy/grub2-theme-preview ‹issue-26-fix-ovmf-image-detection-for-derivative-linux-distros*› 
╰─$ grub2-theme-preview --verbose --debug /boot/grub/themes/EndeavourOS                                                                          1 ↵
INFO: Appending to fonts to load: unifont-regular-16.pf2
INFO: [Errno 13] Permission denied: '/boot/grub/grub.cfg'
INFO: Could not read external GRUB config file, falling back to internal example config

>>> grub.cfg <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
loadfont $prefix/fonts/unicode.pf2
loadfont $prefix/themes/DEMO/unifont-regular-16.pf2
insmod all_video
insmod gfxterm
insmod png
insmod tga
insmod jpeg

menuentry 'Debian' --class debian --class gnu-linux --class linux --class gnu --class os {
    reboot
}

menuentry 'Gentoo' --class gentoo --class gnu-linux --class linux --class gnu --class os {
    reboot
}

menuentry "Memtest86+" {
    reboot
}

submenu 'Reboot / Shutdown' {
    menuentry Reboot { reboot }
    menuentry Shutdown { halt }
}

set default=0
set timeout=30
terminal_output gfxterm
set theme=$prefix/themes/DEMO/theme.txt
>>> grub.cfg <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/home/lorin/.local/lib/python3.9/site-packages/grub2_theme_preview/__main__.py", line 462, in main
    _inner_main(options)
  File "/home/lorin/.local/lib/python3.9/site-packages/grub2_theme_preview/__main__.py", line 388, in _inner_main
    raise OSError(errno.ENOENT,
FileNotFoundError: [Errno 2] OVMF image file "/usr/share/OVMF/OVMF_CODE.fd" (provided by package "ovmf") missing, please install
ERROR: [Errno 2] OVMF image file "/usr/share/OVMF/OVMF_CODE.fd" (provided by package "ovmf") missing, please install
(venv) 
```

**Comment by hartwork** [comment]
@melorin4 your output shows that you are running old code (e.g. because text "provided by package" no longer exists) and different commands. I'm having a bit of trouble understanding what you are doing exactly, e.g. why is there `yay -S venv` in the output? `venv` is a builtin Python module (not a distro package) and `python3 -m venv venv` creates a virtualenv named "venv" in the current directory.

Could you please try again with…
```
cd "$(mktemp -d)"
git clone --branch issue-26-fix-ovmf-image-detection-for-derivative-linux-distros https://github.com/hartwork/grub2-theme-preview
cd grub2-theme-preview/
python3 -m venv venv
source venv/bin/activate
pip install -e .
grub2-theme-preview --verbose --debug /boot/grub/themes/EndeavourOS
```
…please? If any line in that listing is not clear, I am happy to explain in more detail. Thanks! :pray:

**Comment by hartwork** [comment]
@melorin4 I have just released version 2.3.0 with the fix from #27 included to PyPI and mailed the package maintainer for AUR. I consider this issue fixed and I'll hence close the ticket as fixed but please report back if you run into this issue again or anything else. Thank you! :pray:

**Comment by hartwork** [comment]
@melorin4 I just checked: Version 2.3.0 with the fix from #27 is in AUR by now. If you have a minute, I'd be curious how version 2.3.0 works for you.

**Comment by melorin4** [comment]
Thank you, but I recently hopped over to another distro that isn't Arch based so I no longer have access to the AUR.

**Comment by hartwork** [comment]
@melorin4 interesting! What did you move to — Gentoo, nixOS, Fedora, Debian, …? :smiley: Only few distributions [have grub2-theme-preview packaged](https://repology.org/project/grub2-theme-preview/versions) so it will take something like `pip install --user grub2-theme-preview` then most likely. Let me know if anything doesn't work on that new distro of yours.

**Comment by melorin4** [comment]
I moved over to Void! Doing pip install  --user grub2-theme-preview worked for me :)

**Comment by hartwork** [comment]
I see! Checking https://voidlinux.org/packages/ it doesn't seem like they would have edk2-ovmf packaged which is in some disagreement with https://github.com/void-linux/void-packages/pull/11392/files . The paths I see at https://github.com/void-linux/void-packages/pull/11392/files#diff-2e0a2e7e5b7021e3527a529645453f25b9f3ab9f2fc5261c600ae71a16aee55cR72 are not yet supported by grub2-theme-preview to my understanding. Did grub2-theme-preview work on Void as expected?

**Comment by hartwork** [comment]
PS: Related comment at https://github.com/void-linux/void-packages/issues/11243#issuecomment-804053620

**Comment by melorin4** [comment]
Yep, it worked just fine

**Comment by hartwork** [comment]
Do you have hardware without EFI? Did the output say where the `OVMF_CODE.fd` image was taken from?
