### ISSUE TITLE
grub2-theme-preview not working with BTRFS subvolume and/or UUID 

### ISSUE THREAD

**Issue by oshunluvr** [hartwork/grub2-theme-preview#283]
grub2-theme-preview installed to KDEneon User Edition fully updated. Installation is on BTRFS file system. Boot subvolume is @KDEneon. grub2-theme-preview fails with these errors:

```
error: no such device: <btrfs file system UUID here>.
error: file `/@KDEneon/boot/grub/themes/breeze/hack-bold-32.pf2` not found.
~~~above line repeated for each font in theme ---
error: not a directory.

Press any key to continue...
```
I attempt to circumvent the errors by linking '@KDEneon' to the subvolume and also by mounting the subvolume at @KDEneon. Both of these actions resulted in the theme path being available as shown in the error messages, however, the same errors reoccurred. 

At this point it is unknown to me if the errors stem from the UUID being using in grub.cfg or are related to the use of BTRFS subvolumes.

**Comment by hartwork** [comment]
Hi @oshunluvr, I have no experience with BTRFS and not easy access to it. I would expect raw `/boot` instead of /@KDEneon/boot/` and I have no idea where that is coming from. You could try adding `--debug --verbose` to the invocation and see if that gives any extra clues.

**Comment by hartwork** [comment]
Closing for no reply, lack of details, and no way to reproduce myself…
