### ISSUE TITLE
Feature Request: Please add support for custom configs

### ISSUE THREAD

**Issue by Natetronn** [hartwork/grub2-theme-preview#29]
Features request:

Please add support for custom configs files. For example, custom.cfg, liveiso.cfg etc. Then we could do the following wildcard match for .cfg file name:

`grub2-theme-preview --grub-cfg /boot/grub{2,}/*.cfg /usr/share/grub/themes/manjaro`

And or just pass multiple paths directly.

And or there could be a --grub-custom-cfg flag, where we pass one or multiple custom config paths.

Thanks!

**Comment by hartwork** [comment]
Hi @Natetronn, I'm not sure I understand the idea, yet. It is common to have `grub-mkconfig` write one single combined `grub.cfg` file. What is the idea behind allowing multiple .cfg files? What would be a practical example of a case like that, and how would these files interact? Please elaborate. Thank you! :pray:

**Comment by Natetronn** [comment]
Hi @hartwork , thanks for the quick reply!

> You can add additional custom menu entries by editing /etc/grub.d/40_custom and re-generating /boot/grub/grub.cfg. Or you can create /boot/grub/custom.cfg and add them there. Changes to /boot/grub/custom.cfg do not require re-running grub-mkconfig, since /etc/grub.d/41_custom adds the necessary source statement to the generated configuration file.

[Source](https://wiki.archlinux.org/title/GRUB#Configuration)

 /etc/grub.d/41_custom adds the following to the bottom of /boot/grub/grub.cfg
```
#!/bin/sh
cat <<EOF
if [ -f  \${config_directory}/custom.cfg ]; then
  source \${config_directory}/custom.cfg
elif [ -z "\${config_directory}" -a -f  \$prefix/custom.cfg ]; then
  source \$prefix/custom.cfg
fi
EOF
```
From there, you can create a custom.cfg file, which when adding new menuentry to it, you don't need to re-run update-grub or grub-mkconfig etc.

On top of that, you can add custom configs menuentry to the custom.cfg, like so:

```
menuentry 'Live ISOs' --class iso {
	search --no-floppy --set=root --file /boot/grub/liveiso.cfg
	configfile /boot/grub/liveiso.cfg
}
```
Which calls another custom config, in this case /boot/grub/liveiso.cfg. Then in liveiso.cfg I have the following:

```
menuentry 'Manjaro Live ISO - wdusb' --class manjaro {
    set isofile="/ISO/Manjaro/manjaro-kde-21.1.6-211017-linux513.iso"
    set gpu="nonfree"
    search --no-floppy -f --set=root $isofile
    probe -u $root --set=uuid
    set drive="/dev/disk/by-uuid/$uuid"
    loopback loop $isofile
    linux  (loop)/boot/vmlinuz-x86_64 img_dev=$drive img_loop=$isofile driver=$gpu tz=utc lang=en_us keytable=us
    initrd  (loop)/boot/intel_ucode.img (loop)/boot/initramfs-x86_64.img
}

menuentry 'Manjaro Live Minimal ISO - wdusb' --class manjaro {
    set isofile="/ISO/Manjaro/Minimal/manjaro-kde-21.1.6-minimal-211017-linux513.iso"
    set gpu="nonfree"
    search --no-floppy -f --set=root $isofile
    probe -u $root --set=uuid
    set drive="/dev/disk/by-uuid/$uuid"
    loopback loop $isofile
    linux  (loop)/boot/vmlinuz-x86_64 img_dev=$drive img_loop=$isofile driver=$gpu tz=utc lang=en_us keytable=us
    initrd  (loop)/boot/intel_ucode.img (loop)/boot/initramfs-x86_64.img
}

menuentry 'Manjaro Live Sway ISO - wdusb' --class manjaro {
    set isofile="/ISO/Manjaro/Sway/manjaro-sway-21.1.0-211026-linux514.iso"
    set gpu="nonfree"
    search --no-floppy -f --set=root $isofile
    probe -u $root --set=uuid
    set drive="/dev/disk/by-uuid/$uuid"
    loopback loop $isofile
    linux  (loop)/boot/vmlinuz-x86_64 img_dev=$drive img_loop=$isofile driver=$gpu tz=utc lang=en_us keytable=us
    initrd  (loop)/boot/intel_ucode.img (loop)/boot/initramfs-x86_64.img
}
```
In this case I have a back up Live ISO at my disposal, should I need to chroot or something and I was also testing Sway. I have many other entries in custom.cfg as well, tools and such, but I won't pollute this post with more. I hope this is enough for you to understand the basic the idea.

One benefit of doing it this way, versus adding the entry directly to custom.cfg, is that you then have some separation of concerns, even though when it's all said and done, the 41_custom script pulls from custom.cfg and it gets generated all in the end. That is, it doesn't matter if you separate or not separate your menuentries into separate custom config files but, it's a nice way of doing it. 

Aside: I have another custom config called gpu-switcher.cfg, where I the two menu entries launch either the Nouveau or Nvida driver etc.

I hope that all makes sense.

**Comment by hartwork** [comment]
To me that sounds like we need _some way_ to put arbitrary files at custom locations into the Grub 2 rescue image. `grub2-theme-preview` already passes…

- `boot/loader=/boot/loader/`
- `boot/grub/grub.cfg=[tmpdir]/grub.cfg`
- `boot/grub/themes/DEMO/=[themedir]`

to `grub-mkrescue` to make it include these files. So if we allow appending new `target=/source` entries to that list, that should cover your case as well. True? What do you think?

**Comment by Natetronn** [comment]
If I'm following you correctly, I think that may work.

I'm happy to edit main.py directly and give it a test, if you'd be willing to send me the code and lines I need to edit? Then I can confirm it's working or not. 

Whatever you need to make it easier, I'll do my best.

**Comment by Natetronn** [comment]
It is possible we just need to set the config_directory variable?

**Comment by Natetronn** [comment]
Okay, looks like grub-mkrescue doesn't have a config_directory flag for it to be set there:

https://www.commandlinux.com/man-page/man1/grub-mkrescue.1.html

Sorry, trying to better understand how everything ties into each other.

**Comment by Natetronn** [comment]
I tried setting the `config_directory` to see what would happen (around line 120). It didn't seem to help. Not sure I'm doing it correctly, though:

```
def _make_grub_cfg_load_our_theme(grub_cfg_content, source_type, resolution_or_none, font_files_to_load, timeout_seconds):
    # NOTE: The last font loaded becomes the default/fallback font
    #       So if we load fonts first, the remaining default font
    #       will remain unchanged and the theme will display unchanged.
    prolog_chunks = [
            'loadfont $prefix/fonts/unicode.pf2',
            'set config_directory=($root)/boot/grub',
            ]
```
I guess I don't understand why the custom script in grub.cfg doesn't pick up the other entries.

**Comment by hartwork** [comment]
@Natetronn now that GitHub is back up, could you give pull request #30 a try?
Command `grub2-theme-preview --verbose --add foo1/foo2=/bar1/bar2 --add foo3/foo4=/bar3/bar4 /usr/share/grub/themes/Axiom/` would be example use of the feature.

**Comment by Natetronn** [comment]
@hartwork thanks for working on this! Seems to be working. 

This is what I started with, which worked (mostly):

`grub2-theme-preview --verbose --grub-cfg /boot/grub/grub.cfg --add /boot/grub/custom.cfg=/boot/grub/custom.cfg /usr/share/grub/themes/manjaro`

![grub-viewer](https://user-images.githubusercontent.com/582149/143722301-984072bc-e766-4f3b-a0c5-3e22567f33f1.png)

Of course, the submenus for liveiso and gpu-switcher weren't available, so I added them with two more --add flags like so:

`grub2-theme-preview --verbose --grub-cfg /boot/grub/grub.cfg --add /boot/grub/custom.cfg=/boot/grub/custom.cfg --add /boot/grub/gpu-switcher.cfg=/boot/grub/gpu-switcher.cfg --add /boot/grub/liveiso.cfg=/boot/grub/liveiso.cfg /usr/share/grub/themes/manjaro`

![grub-viewer-gpu-switcher](https://user-images.githubusercontent.com/582149/143722368-5cec9a5d-fd72-4b00-9211-6ae0ad5cfca2.png)
![grub-viewer-liveiso](https://user-images.githubusercontent.com/582149/143722370-db604799-b6c2-4af3-99a9-39eb7f7237cc.png)

And that worked!

Thanks for jumping on this so quickly and letting me try to understand how it all worked (my extra comments above lol.) I really appropriate it and just the work you put into this just in general.

**Comment by hartwork** [comment]
@Natetronn thanks for trying the pull request, this feature has now hit PyPI with a new release 2.4.0.

**Comment by Natetronn** [comment]
Awesome! What a cool way to test grub themes and menu entries, even custom ones ;-)
