### ISSUE TITLE
Suggestion: "full" qemu is a requirement

### ISSUE THREAD

**Issue by WilliamKappler** [hartwork/grub2-theme-preview#323]
This is less an issue and more of a suggestion: you should consider documenting in your installation requirements that the qemu version must be qemu-full if there is a choice. On Arch, qemu defaults to qemu-base, which at the very least doesn't work as you intend it to.

It seems qemu-base lacks visual systems and reverts to opening a VNC server. I'm not sure if that actually works if one is to connect to it with a VNC client but it definitely doesn't make sense from a user perspective.

For people like myself with no idea how qemu works, it's really hard to get this right without debugging what's going wrong.

**Comment by hartwork** [comment]
@WilliamKappler how do you feel about pull request #325 for a fix?

**Comment by WilliamKappler** [comment]
That seems like it would be helpful.

Other than that minor bit of confusion, the program seems to work great. Good job!

**Comment by hartwork** [comment]
@WilliamKappler excellent, merged, glad to hear :pray:
