### ISSUE TITLE
"ERROR: 'NoneType' object is not iterable" when not specifying --add.

### ISSUE THREAD

**Issue by txhx38** [hartwork/grub2-theme-preview#33]
### FIXED:
`__main__.py:440`
```python
if options.addition_requests:
    assemble_cmd += options.addition_requests
```

### PREVIOUS:
`__main__.py:440`
```python
assemble_cmd += options.addition_requests
```

**Comment by hartwork** [comment]
That's embarrasing, thanks for the report! Expect a fix today.

**Comment by hartwork** [comment]
Fix merged to `master`and 2.4.2 pushed to PyPI.

@Natetronn any chance you could bump the Arch package? This oversight of mine is a bit of a bummer.

**Comment by Natetronn** [comment]
Thanks for the heads up!

Bumped to 2.4.2 - https://aur.archlinux.org/packages/grub2-theme-preview/

**Comment by hartwork** [comment]
@Natetronn thank you! :pray:
