### ISSUE TITLE
Option "--resolution=" does not work

### ISSUE THREAD

**Issue by Lowrida** [hartwork/grub2-theme-preview#64]
When i use the --resolution option it does not work. I compared both outputs with --debug and noticed that your program puts the "set gfxmode=" to the top. But down the line the original "set  gfxmode=auto" is still there! So it sets it to my resolution, but further down the line it is set back to auto..
Maybe it would be better if your program first search for an existing, and if found then replace it. If not found, then set to the top were it is now.

![screenshot-jpg-JPEG-afbeelding-1167-×-591-pixels-](https://user-images.githubusercontent.com/53632533/166140287-c134366f-b850-48b5-a3bb-1a2e718026f4.png)

**Comment by Lowrida** [comment]
Complete output log

[preview-theme.log](https://github.com/hartwork/grub2-theme-preview/files/8598631/preview-theme.log)

**Comment by hartwork** [comment]
@Lowrida that's a nice report, we will need to get rid of the `set gfxmode=auto` then I guess. Thanks! :+1:

**Comment by hartwork** [comment]
@Lowrida there is pull request #65 now with instructions how to try it out locally. Please let me know if this fix makes things work for you. Thanks! :+1:

**Comment by Lowrida** [comment]
Btw i tried a custom grubconfig with "set gfxmode=auto" replaced by a resolution and it still does not change the qemu window!

**Comment by hartwork** [comment]
@Lowrida you could try with display `gtk` or with display `sdl` and see if either is affected.

I put precise instructions at https://github.com/hartwork/grub2-theme-preview/pull/65#issue-1222148529 . With those, it should be running off the branch in 5 seconds.

**Comment by Lowrida** [comment]
I tried all the display options, but that made no difference. On my system i get the "sdl is not supported" message. Only gtk does not gave me an error, but also did nothing to change any resolution.

For what it's word. I manually edited a custom grub config and removed all the "set gfxmode=" lines and added a new one on top of the config and tested that with any resolution possible and it does not change anything! The resolution thing does nothing at all on my system i guess.

But now that i have fullscreen mode working, for me this is less important.

As i said in another post. If your solution will fix the bug you should implement it in an upcoming update!

**Comment by hartwork** [comment]
@Lowrida the way I read https://github.com/hartwork/grub2-theme-preview/issues/63#issuecomment-1114306192 problem "--resolution= not working" should be gone now when passing `--vga virtio` with version 2.7.0. Can you confirm?

**Comment by hartwork** [comment]
> @Lowrida the way I read [#63 (comment)](https://github.com/hartwork/grub2-theme-preview/issues/63#issuecomment-1114306192) problem "--resolution= not working" should be gone now when passing `--vga virtio` with version 2.7.0. Can you confirm?

@Lowrida can you confirm?

**Comment by hartwork** [comment]
> > @Lowrida the way I read [#63 (comment)](https://github.com/hartwork/grub2-theme-preview/issues/63#issuecomment-1114306192) problem "--resolution= not working" should be gone now when passing `--vga virtio` with version 2.7.0. Can you confirm?
> 
> @Lowrida can you confirm?

@Lowrida any news?

**Comment by hartwork** [comment]
Closing because of no response for months. Happy to re-open if the issues turns out to still exist on `master`.

**Comment by Lowrida** [comment]
And this was no respons??? 

```
Hi, sorry for my late response, i totally missed your previous post! I will let you know asap!

edit: Funny.. i have no clue how i got your program installed last time? I can't seem to get it to update!?
I have cloned the git, but not clear how to make it.. with pip says it does, but when i check the program it is still the old one without the 2 extra options.
```

**Comment by hartwork** [comment]
> edit: Funny.. i have no clue how i got your program installed last time? I can't seem to get it to update!?
> I have cloned the git, but not clear how to make it.. with pip says it does, but when i check the program it is still the old one without the 2 extra options.

@Lowrida if you're still interested, there are detailed instructions at https://github.com/hartwork/grub2-theme-preview/pull/65#issue-1222148529 installing into a fresh virtualenv. Just the clone statement will need slight adjustment.
