### ISSUE TITLE
Address QEMU warning "Image format was not specified" (volunteers welcome)

### ISSUE THREAD

**Issue by hartwork** [hartwork/grub2-theme-preview#7]
```
[..]
# qemu-system-x86_64 -hda /tmp/tmpS3A839/grub2_theme_demo.img
WARNING: Image format was not specified for '/tmp/tmpS3A839/grub2_theme_demo.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```

**Comment by hvfbtr** [comment]
Having the same problem. Did you find an answer?

**Comment by hartwork** [comment]
Hello @hvfbtr, the commit above fixed it for me. I just release version 1.2.1 with the fix. Closing.

**Comment by s777s** [comment]
How should I specify it?
-hda my.img,format=raw 
gives me 'my.img,format=raw': No such file or directory
and -hda my.img format=raw
gives me "...probing guessed raw. ..." again.

**Comment by hartwork** [comment]
Hello @s777s,
please check [the command line usage of grub2-theme-preview](https://github.com/hartwork/grub2-theme-preview#usage). There is no need to specify anything like `-hda`, as that is done for you, internally.
Best, Sebastian

**Comment by yjqg6666** [comment]
$ qemu-system-x86_64 -drive format=raw,file=OSASK-Linux/src/helloos.img 
reference: https://unix.stackexchange.com/questions/276480/booting-a-raw-disk-image-in-qemu

**Comment by JamesTheAwesomeDude** [comment]
So..does this make `-hda` useless for anything which might require modifying the boot sector?

**Comment by vedvarshith** [comment]
in media what should we give we need to give the x.img i told x.img because i wat to install mac in qemu

**Comment by vedvarshith** [comment]
look i got a screen shot
![Screenshot_2020-10-15_19-06-10](https://user-images.githubusercontent.com/70155237/96136899-926abd80-0f19-11eb-911c-8bdab55e25f3.png)

**Comment by vedvarshith** [comment]
look at the last error in the screen shot
![Screenshot_2020-10-15_19-08-07](https://user-images.githubusercontent.com/70155237/96137050-c80fa680-0f19-11eb-9746-1bb8884fc42b.png)

**Comment by vedvarshith** [comment]
please can you tell me how to fix this

**Comment by Shivaraj199** [comment]
$ qemu-system-riscv64 -nographic -M microchip-icicle-kit -sd sdcard.img

 Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
         
and then it got stuck, what am i doing wrong?

**Comment by hartwork** [comment]
@Shivaraj199 your question does not show any relation to grub2-theme-preview, so it is out of place here, plus this ticket is long closed. Please find some active QEMU mailing list or forum for help, thank you.

**Comment by ziyan-zhang** [comment]
> How should I specify it? -hda my.img,format=raw gives me 'my.img,format=raw': No such file or directory and -hda my.img format=raw gives me "...probing guessed raw. ..." again.
> 
> Updated: ok, found the answer on gentoo forum: -drive file=my.img,index=0,media=disk,format=raw
> 
> And I was unable to find how to solve this problem in official wiki. I use Arch with qemu 2.6.0-1 from official repos.

Thank you, I also solved the warning according to your method. I think maybe qemu does not recommend users to use -hda, -hdb to specify the disk?
