### ISSUE TITLE
Custom Fonts Not Loading

### ISSUE THREAD

**Issue by stevensonmt** [hartwork/grub2-theme-preview#87]
I think this is a different issue than referenced at [#19](https://github.com/hartwork/grub2-theme-preview/issues/19) as when I enter the grub shell and run `lsfonts` I only get the entry `Unifont Regular 16`.
I have a custom font defined in `/etc/default/grub` with `GRUB_FONT=/boot/grub/fonts/Font1.pf2` and another font called for in my `theme.txt` as the `item_font = "Font2 14"`. I have tried with and without a second line in `/etc/default/grub` for `GRUB_FONT=/boot/grub/fonts/Font2.pf2`. When I boot the system for real and enter the grub shell `lsfonts` shows Font1 loaded.

**Comment by stevensonmt** [comment]
Sorry. Font not copied to correct directory.

**Comment by hartwork** [comment]
@stevensonmt thanks for the update! :+1:
