### ISSUE TITLE
Timeout notification not showing up?

### ISSUE THREAD

**Issue by vitalogy** [hartwork/grub2-theme-preview#9]
Hi,

i created a grub2-theme for gentoo, but the timeout notification shows not up in QEMU, neither the progrees_bar nor the quick test with the circular_progress. The same theme with Grub2 on my real machine shows me the progress_bar.So, is the timeout notification working with QEMU at all?

You can have a look at my repo:
https://github.com/vitalogy/grub2-theme-gentoo

The Screenshot is taken from QEMU, as you can see, there is no progress_bar.

And thanks for this little programm, it saves a lot of time.

**Comment by hartwork** [comment]
Hi!
Does your disk have the same version of GRUB 2.x installed as is used with grub2-theme-preview?
(I'm thinking the feature could be broken in latest releases of GRUB but you are running an older, working version in your MBR.)
It could take a few days until I get to really debugging that myself. I'm happy about any more debugging or details you could provide.
Thanks, S

**Comment by vitalogy** [comment]
hey,
my system is a few days old. So i bought a new SSD and made a fresh install.
The grub-version on my SSD should be the same, as i am using with QEMU ... but will check this.

**Comment by vitalogy** [comment]
installed grub-version on SSD and installed grub-version in the system are the same

```
# emerge -pv grub

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] sys-boot/grub-2.02_beta2-r7:2::gentoo  USE="fonts multislot nls sdl themes truetype -debug -device-mapper -doc -efiemu -libzfs -mount -static {-test}" GRUB_PLATFORMS="efi-64 pc qemu -coreboot -efi-32 -emu -ieee1275 -loongson -multiboot -qemu-mips -uboot -xen" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB
```

**Comment by hartwork** [comment]
To my understanding, the relevant GRUB modules are:
* progress bar -> progress module
* circular progress -> gfxmenu module

Inspecting the rescue image that is generated over here, it _does_ contain both modules:
```
# find /mnt/tmp0wRpNf/boot/grub/ | grep -E '(gfxmenu|progress).mod'
/mnt/tmp0wRpNf/boot/grub/i386-pc/gfxmenu.mod
/mnt/tmp0wRpNf/boot/grub/i386-pc/progress.mod
```

**Comment by hartwork** [comment]
It turned out that I had put in
```
set timeout=-1
```
so that the QEMU preview would not close quickly. A side effect is, that it disables progress indicators. I didn't think of that. Many thanks for the report! I justed fixed it.

**Comment by hartwork** [comment]
Bumped to 1.3.1 in Gentoo, needs a moment to sync.
```
+*grub2-theme-preview-1.3.1 (13 Jul 2015)
+
+  13 Jul 2015; Sebastian Pipping <......>
+  +grub2-theme-preview-1.3.1.ebuild:
+  Bump to 1.3.1 with support for progress indicators
+
```
Closing.

Once you're happy with that theme of yours, let's add an ebuild for it to the [grub2-themes-overlay](https://github.com/gentoo/grub2-themes-overlay).

Best, S
